(function(g){var window=this;'use strict';var fYy=function(m){m.publish("autonavvisibility")},uBg=function(m,M){m.FC("onAutonavCoundownStarted",M)},SzT=function(m){return m.isBackground()&&m.wA()},E5s=function(m){var M,e,I;
return m==null?void 0:(M=m.playerOverlays)==null?void 0:(e=M.playerOverlayRenderer)==null?void 0:(I=e.autoplay)==null?void 0:I.playerOverlayAutoplayRenderer},QD=function(m){var M=m.K(),e=M.B;
g.a.call(this,{j:"a",J:"ytp-autonav-suggestion-card",N:{href:"{{url}}",target:e?M.nE:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{j:"div",x7:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],N:{style:"{{background}}"},W:[{j:"div",N:{"aria-label":"{{timestamp}}"},x7:["ytp-autonav-timestamp"],Mr:"{{duration}}"},{j:"div",x7:["ytp-autonav-live-stamp"],Mr:"En vivo"},
{j:"div",x7:["ytp-autonav-upcoming-stamp"],Mr:"Pr\u00f3ximamente"},{j:"div",J:"ytp-autonav-list-overlay",W:[{j:"div",J:"ytp-autonav-mix-text",Mr:"Mix"},{j:"div",J:"ytp-autonav-mix-icon"}]}]},{j:"div",x7:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Mr:"{{title}}"},{j:"div",x7:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Mr:"{{author}}"},{j:"div",x7:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Mr:"{{views_and_publish_time}}"}]});this.G=
m;this.suggestion=null;this.L=e;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},s$=function(m,M){M=M===void 0?!1:M;
g.a.call(this,{j:"div",J:"ytp-autonav-endscreen-countdown-overlay"});var e=this;this.X=M;this.cancelCommand=this.C=void 0;this.D=0;this.container=new g.a({j:"div",J:"ytp-autonav-endscreen-countdown-container"});g.D(this,this.container);this.container.CE(this.element);M=m.K();var I=M.B;this.G=m;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.Z(m,"videodatachange",this.onVideoDataChange);this.L=new g.a({j:"div",J:"ytp-autonav-endscreen-upnext-container",N:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{j:"div",J:"ytp-autonav-endscreen-upnext-header"},{j:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",Mr:"{{autoplayAlternativeHeader}}"},{j:"a",J:"ytp-autonav-endscreen-link-container",N:{href:"{{url}}",target:I?M.nE:""},W:[{j:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",N:{style:"{{background}}"},W:[{j:"div",N:{"aria-label":"{{timestamp}}"},x7:["ytp-autonav-timestamp"],
Mr:"{{duration}}"},{j:"div",x7:["ytp-autonav-live-stamp"],Mr:"En vivo"},{j:"div",x7:["ytp-autonav-upcoming-stamp"],Mr:"Pr\u00f3ximamente"}]},{j:"div",J:"ytp-autonav-endscreen-video-info",W:[{j:"div",J:"ytp-autonav-endscreen-premium-badge"},{j:"div",J:"ytp-autonav-endscreen-upnext-title",Mr:"{{title}}"},{j:"div",J:"ytp-autonav-endscreen-upnext-author",Mr:"{{author}}"},{j:"div",J:"ytp-autonav-view-and-date",Mr:"{{views_and_publish_time}}"},{j:"div",J:"ytp-autonav-author-and-view",Mr:"{{author_and_views}}"}]}]}]});
g.D(this,this.L);this.L.CE(this.container.element);I||this.Z(this.L.ju("ytp-autonav-endscreen-link-container"),"click",this.yA);this.G.createClientVe(this.container.element,this,115127);this.G.createClientVe(this.L.ju("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.a({j:"div",J:"ytp-autonav-overlay"});g.D(this,this.overlay);this.overlay.CE(this.container.element);this.Y=new g.a({j:"div",J:"ytp-autonav-endscreen-button-container"});g.D(this,this.Y);this.Y.CE(this.container.element);
this.cancelButton=new g.a({j:"button",x7:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],N:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Mr:"Cancelar"});g.D(this,this.cancelButton);this.cancelButton.CE(this.Y.element);this.cancelButton.listen("click",this.Iw,this);this.G.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.a({j:"a",x7:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
"ytp-autonav-endscreen-upnext-button-rounded"],N:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente video"},Mr:"Reproducir ahora"});g.D(this,this.playButton);this.playButton.CE(this.Y.element);this.playButton.listen("click",this.yA,this);this.G.createServerVe(this.playButton.element,this.playButton,!0);(M=this.G.getVideoData())&&n50(this,M);this.B=new g.vR(function(){PyT(e)},500);
g.D(this,this.B);this.jr();this.Z(m,"autonavvisibility",this.jr);this.G.U("web_autonav_color_transition")&&(this.Z(m,"autonavchange",this.Y3),this.Z(m,"onAutonavCoundownStarted",this.hHy))},rC=function(m){var M=m.G.W5(!0,m.G.isFullscreen());
g.Zn(m.container.element,"ytp-autonav-endscreen-small-mode",m.o3(M));g.Zn(m.container.element,"ytp-autonav-endscreen-is-premium",!!m.suggestion&&!!m.suggestion.VTt);g.Zn(m.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!m.G.I2());g.Zn(m.G.getRootNode(),"countdown-running",m.CO());g.Zn(m.container.element,"ytp-player-content",m.G.I2());g.I_(m.overlay.element,{width:M.width+"px"});if(!m.CO()){m.G.I2()?BX6(m,Math.round(h8T(m)/1E3)):BX6(m);M=!!m.suggestion&&!!m.suggestion.AN;var e=m.G.I2()||
!M;g.Zn(m.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!e&&M);g.Zn(m.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",e&&!M);m.Y.QE(m.G.I2());g.Zn(m.element,"ytp-enable-w2w-color-transitions",wBf(m))}},PyT=function(m){var M=h8T(m),e=Math,I=e.min;
var t=m.D?Date.now()-m.D:0;e=I.call(e,t,M);BX6(m,Math.ceil((M-e)/1E3));M-e<=500&&m.CO()?m.select(!0):m.CO()&&m.B.start()},h8T=function(m){if(m.G.isFullscreen()){var M;
m=(M=m.G.getVideoData())==null?void 0:M.Ip;return m===-1||m===void 0?8E3:m}return m.G.Tx()>=0?m.G.Tx():g.KE(m.G.K().experiments,"autoplay_time")||1E4},n50=function(m,M){M=M.getWatchNextResponse();
var e,I;M=(e=E5s(M))==null?void 0:(I=e.nextButton)==null?void 0:I.buttonRenderer;m.C=M==null?void 0:M.navigationEndpoint;e=M==null?void 0:M.trackingParams;m.playButton&&e&&m.G.setTrackingParams(m.playButton.element,e)},wBf=function(m){var M;
return!((M=m.G.getVideoData())==null||!M.watchToWatchTransitionRenderer)},BX6=function(m,M){M=M===void 0?-1:M;
m=m.L.ju("ytp-autonav-endscreen-upnext-header");g.nN(m);if(M>=0){M=String(M);var e="A continuaci\u00f3n, en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],I="A continuaci\u00f3n, en $SECONDS".indexOf(e);if(I>=0){m.appendChild(g.S9("A continuaci\u00f3n, en $SECONDS".slice(0,I)));var t=g.uB("span");g.Ya(t,"ytp-autonav-endscreen-upnext-header-countdown-number");g.oD(t,M);m.appendChild(t);m.appendChild(g.S9("A continuaci\u00f3n, en $SECONDS".slice(I+e.length)));return}}g.oD(m,"A continuaci\u00f3n")},qO=
function(m,M){g.a.call(this,{j:"div",
x7:["html5-endscreen","ytp-player-content",M||"base-endscreen"]});this.created=!1;this.player=m},ZQ=function(m){g.a.call(this,{j:"div",
x7:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},W:[{j:"div",J:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{j:"span",J:"ytp-upnext-top",W:[{j:"span",J:"ytp-upnext-header",Mr:"A continuaci\u00f3n"},{j:"span",J:"ytp-upnext-title",Mr:"{{title}}"},{j:"span",J:"ytp-upnext-author",Mr:"{{author}}"}]},{j:"a",J:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente video"},W:[{j:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},W:[{j:"circle",J:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{j:"circle",J:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{j:"path",J:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{j:"span",J:"ytp-upnext-bottom",W:[{j:"span",J:"ytp-upnext-cancel"},{j:"span",J:"ytp-upnext-paused",
Mr:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=m;this.cancelButton=null;this.C=this.ju("ytp-svg-autoplay-ring");this.D=this.notification=this.L=this.suggestion=null;this.B=new g.vR(this.NZ,5E3,this);this.Y=0;var M=this.ju("ytp-upnext-cancel");this.cancelButton=new g.a({j:"button",x7:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Mr:"Cancelar"});g.D(this,this.cancelButton);this.cancelButton.listen("click",
this.DW,this);this.cancelButton.CE(M);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.D(this,this.B);this.api.createClientVe(this.element,this,18788);M=this.ju("ytp-upnext-autoplay-icon");this.Z(M,"click",this.Mm);this.api.createClientVe(M,this,115130);this.tf();this.Z(m,"autonavvisibility",this.tf);this.Z(m,"mdxnowautoplaying",this.HjG);this.Z(m,"mdxautoplaycanceled",this.k9G);g.Zn(this.element,"ytp-upnext-mobile",this.api.K().Y)},o5C=function(m,M){if(M)return M;
if(m.api.isFullscreen()){var e;m=(e=m.api.getVideoData())==null?void 0:e.Ip;return m===-1||m===void 0?8E3:m}return m.api.Tx()>=0?m.api.Tx():g.KE(m.api.K().experiments,"autoplay_time")||1E4},z8d=function(m,M){M=o5C(m,M);
var e=Math,I=e.min;var t=(0,g.uR)()-m.Y;e=I.call(e,t,M);M=M===0?1:Math.min(e/M,1);m.C.setAttribute("stroke-dashoffset",""+-211*(M+1));M>=1&&m.CO()&&m.api.getPresentingPlayerType()!==3?m.select(!0):m.CO()&&m.L.start()},FY=function(m){qO.call(this,m,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.a({j:"div",J:"ytp-suggestion-panel",W:[{j:"div",x7:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Mr:"M\u00e1s videos"}]});this.T=new g.a({j:"div",J:"ytp-suggestions-container"});this.videos=[];this.D=null;this.C=this.X=!1;this.Y=new s$(this.player);g.D(this,this.Y);this.Y.CE(this.element);m.getVideoData().M7?this.L=this.Y:(this.L=new ZQ(m),g.GS(this.player,this.L.element,4),g.D(this,this.L));this.overlay=new g.a({j:"div",
J:"ytp-autonav-overlay-cancelled-state"});g.D(this,this.overlay);this.overlay.CE(this.element);this.B=new g.CV(this);g.D(this,this.B);g.D(this,this.table);this.table.CE(this.element);this.table.show();g.D(this,this.T);this.T.CE(this.table.element);this.hide()},Cl=function(m){var M=m.I2();
M!==m.C&&(m.C=M,fYy(m.player),m.C?(m.Y!==m.L&&m.Y.hide(),m.table.hide()):(m.Y!==m.L&&m.Y.show(),m.table.show()))},TXT=function(m){qO.call(this,m,"videowall-endscreen");
var M=this;this.G=m;this.stills=[];this.D=this.videoData=null;this.B=this.X=!1;this.T=null;g.Q2(this.element,"modern-videowall-endscreen");this.Y=new g.CV(this);g.D(this,this.Y);this.C=new g.vR(function(){g.Q2(M.element,"ytp-show-tiles")},0);
g.D(this,this.C);this.table=new g.rz({j:"div",J:"ytp-modern-endscreen-content"});g.D(this,this.table);this.table.CE(this.element);m.getVideoData().M7?this.L=new s$(m,!0):this.L=new ZQ(m);g.D(this,this.L);g.GS(this.player,this.L.element,4);m.createClientVe(this.element,this,158789);this.hide()},Hz=function(m){return g.ax(m.player)&&m.Vm()&&!m.D},Rk=function(m){var M=m.I2();
M!==m.X&&(m.X=M,fYy(m.player))},XBC=function(m){qO.call(this,m,"subscribecard-endscreen");
this.L=new g.a({j:"div",J:"ytp-subscribe-card",W:[{j:"img",J:"ytp-author-image",N:{src:"{{profilePicture}}"}},{j:"div",J:"ytp-subscribe-card-right",W:[{j:"div",J:"ytp-author-name",Mr:"{{author}}"},{j:"div",J:"html5-subscribe-button-container"}]}]});g.D(this,this.L);this.L.CE(this.element);var M=m.getVideoData();this.subscribeButton=new g.Ow("Suscribirse",null,"Anular suscripci\u00f3n",null,!0,!1,M.R7,M.subscribed,"trailer-endscreen",null,m,!1);g.D(this,this.subscribeButton);this.subscribeButton.CE(this.L.ju("html5-subscribe-button-container"));
this.Z(m,"videodatachange",this.sY);this.sY();this.hide()},Wz=function(m){var M=m.K(),e=g.r5||g.X4?{style:"will-change: opacity"}:void 0,I=M.B,t=["ytp-videowall-still"];
M.Y&&t.push("ytp-videowall-show-text");g.a.call(this,{j:"a",x7:t,N:{href:"{{url}}",target:I?M.nE:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{j:"div",J:"ytp-videowall-still-image",N:{style:"{{background}}"}},{j:"span",J:"ytp-videowall-still-info",N:{"aria-hidden":"true"},W:[{j:"span",J:"ytp-videowall-still-info-bg",W:[{j:"span",J:"ytp-videowall-still-info-content",N:e,W:[{j:"span",J:"ytp-videowall-still-info-title",Mr:"{{title}}"},
{j:"span",J:"ytp-videowall-still-info-author",Mr:"{{author_and_views}}"},{j:"span",J:"ytp-videowall-still-info-live",Mr:"En vivo"},{j:"span",J:"ytp-videowall-still-info-duration",Mr:"{{duration}}"}]}]}]},{j:"span",x7:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},W:[{j:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{j:"span",J:"ytp-videowall-still-listlabel-length",W:[" (",{j:"span",Mr:"{{playlist_length}}"},")"]}]},{j:"span",x7:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},W:[{j:"span",J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{j:"span",J:"ytp-videowall-still-listlabel-length",Mr:" (50+)"}]}]});this.suggestion=null;this.Y=I;this.api=m;this.L=new g.CV(this);g.D(this,this.L);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.L.Z(m,"videodatachange",this.onVideoDataChange);m.createServerVe(this.element,this);this.onVideoDataChange()},k9=function(m){qO.call(this,m,"videowall-endscreen");
var M=this;this.G=m;this.D=0;this.stills=[];this.B=this.videoData=null;this.C=this.T=!1;this.S=null;this.Y=new g.CV(this);g.D(this,this.Y);this.X=new g.vR(function(){g.Q2(M.element,"ytp-show-tiles")},0);
g.D(this,this.X);var e=new g.a({j:"button",x7:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Anterior"},W:[g.Ub()]});g.D(this,e);e.CE(this.element);e.listen("click",this.Ha,this);this.table=new g.rz({j:"div",J:"ytp-endscreen-content"});g.D(this,this.table);this.table.CE(this.element);e=new g.a({j:"button",x7:["ytp-button","ytp-endscreen-next"],N:{"aria-label":"Siguiente"},W:[g.Vx()]});g.D(this,e);e.CE(this.element);e.listen("click",this.tT,this);m.getVideoData().M7?this.L=new s$(m,!0):this.L=
new ZQ(m);g.D(this,this.L);g.GS(this.player,this.L.element,4);m.createClientVe(this.element,this,158789);this.hide()},U$=function(m){return g.ax(m.player)&&m.Vm()&&!m.B},VD=function(m){var M=m.I2();
M!==m.T&&(m.T=M,fYy(m.player))},pBf=function(m,M){g.a.call(this,{j:"button",
x7:["ytp-watch-on-youtube-button","ytp-button"],Mr:"{{content}}"});this.G=m;this.buttonType=this.buttonType=M;this.A1();this.buttonType===2&&g.Q2(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.A1);this.QE(!0)},NO=function(m){qO.call(this,m,"watch-again-on-youtube-endscreen");
this.watchButton=new pBf(m,1);g.D(this,this.watchButton);this.watchButton.CE(this.element);g.Rnm(m)&&(this.L=new g.vF(m),g.D(this,this.L),this.Y=new g.a({j:"div",x7:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],N:{tabIndex:"-1"},W:[this.L]}),g.D(this,this.Y),this.L.CE(this.Y.element),this.Y.CE(this.element));m.createClientVe(this.element,this,156914);this.hide()},Duy=function(m){g.Fh.call(this,m);
var M=this;this.endScreen=null;this.L=this.Y=this.D=!1;this.listeners=new g.CV(this);g.D(this,this.listeners);var e=m.K();m.isEmbedsShortsMode()?this.endScreen=new NO(m):lYy(m)?(this.D=!0,xuZ(this),this.L?this.endScreen=new FY(m):e.U("delhi_modern_endscreen")?this.endScreen=new TXT(m):this.endScreen=new k9(m)):e.MX?this.endScreen=new XBC(m):this.endScreen=new qO(m);g.D(this,this.endScreen);g.GS(m,this.endScreen.element,4);ART(this);this.listeners.Z(m,"videodatachange",this.onVideoDataChange,this);
this.listeners.Z(m,g.$E("endscreen"),function(I){M.onCueRangeEnter(I)});
this.listeners.Z(m,g.Gn("endscreen"),function(I){M.onCueRangeExit(I)})},xuZ=function(m){var M=m.player.getVideoData();
if(!M||m.L===M.Oo&&m.Y===M.M7)return!1;m.L=M.Oo;m.Y=M.M7;return!0},lYy=function(m){m=m.K();
return m.II&&!m.MX&&!m.disableOrganicUi},ART=function(m){m.player.al("endscreen");
var M=m.player.getVideoData();M=new g.Af(Math.max((M.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var e=new g.Af(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});m.player.OU([M,e])};
g.TS.prototype.Tx=g.Xt(8,function(){return this.app.Tx()});
g.WN.prototype.Tx=g.Xt(7,function(){return this.getVideoData().Lm});
g.PY.prototype.wy=g.Xt(6,function(m){this.u5().wy(m)});
g.lz.prototype.wy=g.Xt(5,function(m){this.p6!==m&&(this.p6=m,this.N1())});
g.V(QD,g.a);QD.prototype.select=function(){this.G.XX(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.UV||void 0)&&this.G.logClick(this.element)};
QD.prototype.onClick=function(m){g.k6(m,this.G,this.L,this.suggestion.sessionData||void 0)&&this.select()};
QD.prototype.onKeyPress=function(m){switch(m.keyCode){case 13:case 32:m.defaultPrevented||(this.select(),m.preventDefault())}};g.V(s$,g.a);g.k=s$.prototype;g.k.zl=function(m){this.suggestion!==m&&(this.suggestion=m,g.gE(this.L,m),this.playButton.updateValue("url",this.suggestion.QS()),rC(this))};
g.k.CO=function(){return this.D>0};
g.k.tJ=function(){this.CO()||(this.D=Date.now(),PyT(this),uBg(this.G,h8T(this)),g.Zn(this.G.getRootNode(),"countdown-running",this.CO()))};
g.k.tL=function(){this.Fh();PyT(this);var m=this.L.ju("ytp-autonav-endscreen-upnext-header");m&&g.oD(m,"A continuaci\u00f3n")};
g.k.Fh=function(){this.CO()&&(this.B.stop(),this.D=0)};
g.k.select=function(m){this.G.nextVideo(!1,m===void 0?!1:m);this.Fh()};
g.k.yA=function(m){g.k6(m,this.G)&&(m.currentTarget===this.playButton.element?this.G.logClick(this.playButton.element):m.currentTarget===this.L.ju("ytp-autonav-endscreen-link-container")&&(m=this.L.ju("ytp-autonav-endscreen-link-container"),this.G.logVisibility(m,!0),this.G.logClick(m)),this.C?(this.G.FC("innertubeCommand",this.C),this.Fh()):this.select())};
g.k.Iw=function(){this.G.logClick(this.cancelButton.element);g.pB(this.G,!0);this.cancelCommand&&this.G.FC("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(m,M){n50(this,M);m=M.getWatchNextResponse();var e,I;m=(e=E5s(m))==null?void 0:(I=e.cancelButton)==null?void 0:I.buttonRenderer;this.cancelCommand=m==null?void 0:m.command};
g.k.hHy=function(m){if(wBf(this)){var M=this.G.getVideoData().watchToWatchTransitionRenderer,e=M==null?void 0:M.fromColorPaletteDark;M=M==null?void 0:M.toColorPaletteDark;if(e&&M){var I=this.element;I.style.setProperty("--w2w-start-background-color",g.pm(e.surgeColor));I.style.setProperty("--w2w-start-primary-text-color",g.pm(e.primaryTitleColor));I.style.setProperty("--w2w-start-secondary-text-color",g.pm(e.secondaryTitleColor));I.style.setProperty("--w2w-end-background-color",g.pm(M.surgeColor));
I.style.setProperty("--w2w-end-primary-text-color",g.pm(M.primaryTitleColor));I.style.setProperty("--w2w-end-secondary-text-color",g.pm(M.secondaryTitleColor));I.style.setProperty("--w2w-animation-duration",m+"ms")}g.Zn(this.element,"ytp-w2w-animate",!0)}};
g.k.Y3=function(m){this.G.U("web_autonav_color_transition")&&m!==2&&g.Zn(this.element,"ytp-w2w-animate",!1)};
g.k.jr=function(){var m=this.G.I2();this.X&&this.Bn!==m&&this.QE(m);rC(this);this.G.logVisibility(this.container.element,m);this.G.logVisibility(this.cancelButton.element,m);this.G.logVisibility(this.L.ju("ytp-autonav-endscreen-link-container"),m);this.G.logVisibility(this.playButton.element,m)};
g.k.o3=function(m){return m.width<400||m.height<459};g.V(qO,g.a);g.k=qO.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Vm=function(){return!1};
g.k.I2=function(){return!1};
g.k.TB=function(){return!1};g.V(ZQ,g.a);g.k=ZQ.prototype;g.k.NZ=function(){this.notification&&(this.B.stop(),this.GY(this.D),this.D=null,this.notification.close(),this.notification=null)};
g.k.zl=function(m){this.suggestion=m;g.gE(this,m,"hqdefault.jpg")};
g.k.tf=function(){this.QE(this.api.I2());this.api.logVisibility(this.element,this.api.I2());this.api.logVisibility(this.ju("ytp-upnext-autoplay-icon"),this.api.I2());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.I2())};
g.k.pvr=function(){window.focus();this.NZ()};
g.k.tJ=function(m){var M=this;this.CO()||(g.Yi("a11y-announce","A continuaci\u00f3n "+this.suggestion.title),this.Y=(0,g.uR)(),this.L=new g.vR(function(){z8d(M,m)},25),z8d(this,m),uBg(this.api,o5C(this,m)));
g.rV(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.a.prototype.hide.call(this)};
g.k.CO=function(){return!!this.L};
g.k.tL=function(){this.Fh();this.Y=(0,g.uR)();z8d(this);g.Q2(this.element,"ytp-upnext-autoplay-paused")};
g.k.Fh=function(){this.CO()&&(this.L.dispose(),this.L=null)};
g.k.select=function(m){m=m===void 0?!1:m;if(this.api.K().U("autonav_notifications")&&m&&window.Notification&&typeof document.hasFocus==="function"){var M=Notification.permission;M==="default"?Notification.requestPermission():M!=="granted"||document.hasFocus()||(this.NZ(),this.notification=new Notification("A continuaci\u00f3n",{body:this.suggestion.title,icon:this.suggestion.z4()}),this.D=this.Z(this.notification,"click",this.pvr),this.B.start())}this.Fh();this.api.nextVideo(!1,m)};
g.k.Mm=function(m){!g.wY(this.cancelButton.element,m.target)&&g.k6(m,this.api)&&(this.api.I2()&&this.api.logClick(this.ju("ytp-upnext-autoplay-icon")),this.select())};
g.k.DW=function(){this.api.I2()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.pB(this.api,!0)};
g.k.HjG=function(m){this.api.getPresentingPlayerType();this.show();this.tJ(m)};
g.k.k9G=function(){this.api.getPresentingPlayerType();this.Fh();this.hide()};
g.k.AG=function(){this.Fh();this.NZ();g.a.prototype.AG.call(this)};g.V(FY,qO);g.k=FY.prototype;g.k.create=function(){qO.prototype.create.call(this);this.B.Z(this.player,"appresize",this.uA);this.B.Z(this.player,"onVideoAreaChange",this.uA);this.B.Z(this.player,"videodatachange",this.onVideoDataChange);this.B.Z(this.player,"autonavchange",this.HE);this.B.Z(this.player,"onAutonavCancelled",this.AT);this.onVideoDataChange()};
g.k.show=function(){qO.prototype.show.call(this);(this.X||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.pB(this.player,!1);g.ax(this.player)&&this.Vm()&&!this.D?(Cl(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||SzT(this.player.Az())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.tJ():this.videoData.autonavState===3&&this.L.tL()):(g.pB(this.player,!0),Cl(this));this.uA()};
g.k.hide=function(){qO.prototype.hide.call(this);this.L.tL();Cl(this)};
g.k.uA=function(){var m=this.player.W5(!0,this.player.isFullscreen());Cl(this);rC(this.Y);g.Zn(this.element,"ytp-autonav-cancelled-small-mode",this.o3(m));g.Zn(this.element,"ytp-autonav-cancelled-tiny-mode",this.JH(m));g.Zn(this.element,"ytp-autonav-cancelled-mini-mode",m.width<=400||m.height<=360);this.overlay&&g.I_(this.overlay.element,{width:m.width+"px"});if(!this.C)for(m=0;m<this.videos.length;m++)g.Zn(this.videos[m].element,"ytp-suggestion-card-with-margin",m%2===1)};
g.k.onVideoDataChange=function(){var m=this.player.getVideoData();if(this.videoData!==m&&m){this.videoData=m;m=this.videoData.suggestions;var M=g.HG(this.videoData);M&&(this.L.zl(M),this.L!==this.Y&&this.Y.zl(M));if(m&&m.length)for(M=0;M<$uy.length;++M){var e=$uy[M];if(m&&m[e]){this.videos[M]=new QD(this.player);var I=this.videos[M];e=m[e];I.suggestion!==e&&(I.suggestion=e,g.gE(I,e));g.D(this,this.videos[M]);this.videos[M].CE(this.T.element)}}this.uA()}};
g.k.HE=function(m){m===1?(this.X=!1,this.D=this.videoData.clientPlaybackNonce,this.L.Fh(),this.Bn&&this.uA()):(this.X=!0,this.I2()&&(m===2?this.L.tJ():m===3&&this.L.tL()))};
g.k.AT=function(m){m?this.HE(1):(this.D=null,this.X=!1)};
g.k.Vm=function(){return this.videoData.autonavState!==1};
g.k.o3=function(m){return(m.width<910||m.height<459)&&!this.JH(m)&&!(m.width<=400||m.height<=360)};
g.k.JH=function(m){return m.width<800&&!(m.width<=400||m.height<=360)};
g.k.I2=function(){return this.Bn&&g.ax(this.player)&&this.Vm()&&!this.D};
var $uy=[1,3,2,4];g.V(TXT,qO);g.k=TXT.prototype;g.k.create=function(){qO.prototype.create.call(this);var m=this.player.getVideoData();m&&(this.videoData=m);this.Ev();this.Y.Z(this.player,"appresize",this.Ev);this.Y.Z(this.player,"onVideoAreaChange",this.Ev);this.Y.Z(this.player,"videodatachange",this.onVideoDataChange);this.Y.Z(this.player,"autonavchange",this.Ck);this.Y.Z(this.player,"onAutonavCancelled",this.Ba);m=this.videoData.autonavState;m!==this.T&&this.Ck(m);this.Y.Z(this.element,"transitionend",this.j8)};
g.k.destroy=function(){g.zI(this.Y);g.US(this.stills);this.stills=[];qO.prototype.destroy.call(this);g.rV(this.element,"ytp-show-tiles");this.C.stop();this.T=this.videoData.autonavState};
g.k.Vm=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var m=this.Bn;qO.prototype.show.call(this);g.rV(this.element,"ytp-show-tiles");this.player.K().Y?g.Ka(this.C):this.C.start();(this.B||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.pB(this.player,!1);Hz(this)?(Rk(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||SzT(this.player.Az())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.tJ():this.videoData.autonavState===3&&this.L.tL()):(g.pB(this.player,!0),Rk(this));m!==this.Bn&&
this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var m=this.Bn;qO.prototype.hide.call(this);this.L.tL();Rk(this);m!==this.Bn&&this.player.logVisibility(this.element,!1)};
g.k.j8=function(m){m.target===this.element&&this.Ev()};
g.k.Ev=function(){var m,M,e,I;var t=((m=this.videoData)==null?0:(M=m.suggestions)==null?0:M.length)?(e=this.videoData)==null?void 0:e.suggestions:[(I=this.videoData)==null?void 0:g.HG(I)];if(t.length){M=this.G.W5(!0,this.G.isFullscreen());m=Math.floor((M.width-64+16)/(g.M3(M.width*.27,250,450)+16));M=Math.min(3,Math.floor((M.height-64)/((M.width-64-(m-1)*16)/m*.5625+70)));g.q7(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Q2(this.element,"ytp-modern-endscreen-limit-rows-"+M);g.Zn(this.element,"ytp-modern-endscreen-single-item",m===1);g.Zn(this.element,"ytp-modern-endscreen-row-0",M===0);m=this.table.element;m.ariaLive="polite";this.L.zl(g.HG(this.videoData));this.L instanceof s$&&rC(this.L);g.Zn(this.element,"ytp-endscreen-takeover",Hz(this));Rk(this);M=0;m.ariaBusy="true";e=t.length;for(I=0;I<e;I++){var Y=I%e,b=this.stills[I];b||(b=new g.K_(this.player),this.stills[I]=b,m.appendChild(b.element));g.J7w(b,t[Y]);M++}this.stills.length=
M}};
g.k.onVideoDataChange=function(){var m=this.player.getVideoData(1);this.videoData!==m&&(m!=null&&g.HG(m)?(this.videoData=m,this.Ev()):this.player.It("missg",{vid:(m==null?void 0:m.videoId)||"",cpn:(m==null?void 0:m.clientPlaybackNonce)||""}))};
g.k.TB=function(){return this.L.CO()};
g.k.Ck=function(m){m===1?(this.B=!1,this.D=this.videoData.clientPlaybackNonce,this.L.Fh(),this.Bn&&this.Ev()):(this.B=!0,this.Bn&&Hz(this)&&(m===2?this.L.tJ():m===3&&this.L.tL()))};
g.k.Ba=function(m){if(m){for(m=0;m<this.stills.length;m++)this.G.logVisibility(this.stills[m].element,!0);this.Ck(1)}else this.D=null,this.B=!1;this.Ev()};
g.k.I2=function(){return this.Bn&&Hz(this)};g.V(XBC,qO);XBC.prototype.sY=function(){var m=this.player.getVideoData();this.L.update({profilePicture:m.profilePicture,author:m.author});this.subscribeButton.channelId=m.R7;var M=this.subscribeButton;m.subscribed?M.L():M.Y()};g.V(Wz,g.a);Wz.prototype.select=function(){this.api.XX(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.UV||void 0)&&this.api.logClick(this.element)};
Wz.prototype.onClick=function(m){if(g.lj(this.api.K())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var M=this.suggestion.QS(),e={};g.AW(this.api,e);M=g.Bm(M,e);g.Uo(M,this.api,m)}else g.k6(m,this.api,this.Y,this.suggestion.sessionData||void 0)&&this.select()};
Wz.prototype.onKeyPress=function(m){switch(m.keyCode){case 13:case 32:m.defaultPrevented||(this.select(),m.preventDefault())}};
Wz.prototype.onVideoDataChange=function(){var m=this.api.getVideoData(),M=this.api.K();this.Y=m.Fu?!1:M.B};g.V(k9,qO);g.k=k9.prototype;g.k.create=function(){qO.prototype.create.call(this);var m=this.player.getVideoData();m&&(this.videoData=m);this.Oc();this.Y.Z(this.player,"appresize",this.Oc);this.Y.Z(this.player,"onVideoAreaChange",this.Oc);this.Y.Z(this.player,"videodatachange",this.onVideoDataChange);this.Y.Z(this.player,"autonavchange",this.aK);this.Y.Z(this.player,"onAutonavCancelled",this.yp);m=this.videoData.autonavState;m!==this.S&&this.aK(m);this.Y.Z(this.element,"transitionend",this.lc)};
g.k.destroy=function(){g.zI(this.Y);g.US(this.stills);this.stills=[];qO.prototype.destroy.call(this);g.rV(this.element,"ytp-show-tiles");this.X.stop();this.S=this.videoData.autonavState};
g.k.Vm=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var m=this.Bn;qO.prototype.show.call(this);g.rV(this.element,"ytp-show-tiles");this.player.K().Y?g.Ka(this.X):this.X.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.pB(this.player,!1);U$(this)?(VD(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||SzT(this.player.Az())&&this.player.U("web_player_pip_logging_fix")?this.L.select(!0):this.L.tJ():this.videoData.autonavState===3&&this.L.tL()):(g.pB(this.player,!0),VD(this));m!==this.Bn&&
this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var m=this.Bn;qO.prototype.hide.call(this);this.L.tL();VD(this);m!==this.Bn&&this.player.logVisibility(this.element,!1)};
g.k.lc=function(m){m.target===this.element&&this.Oc()};
g.k.Oc=function(){var m,M,e,I;var t=((m=this.videoData)==null?0:(M=m.suggestions)==null?0:M.length)?(e=this.videoData)==null?void 0:e.suggestions:[(I=this.videoData)==null?void 0:g.HG(I)];if(t.length){g.Q2(this.element,"ytp-endscreen-paginate");var Y=this.G.W5(!0,this.G.isFullscreen());if(m=g.JW(this.G))m=m.b_()?48:32,Y.width-=m*2;var b=Y.width/Y.height;I=96/54;M=m=2;var r=Math.max(Y.width/96,2),q=Math.max(Y.height/54,2);e=t.length;var Z=e*4;for(Z-=4;Z>0&&(m<r||M<q);){var F=m/2,C=M/2,R=m<=r-2&&Z>=
C*4,H=M<=q-2&&Z>=F*4;if((F+1)/C*I/b>b/(F/(C+1)*I)&&H)Z-=F*4,M+=2;else if(R)Z-=C*4,m+=2;else if(H)Z-=F*4,M+=2;else break}I=!1;Z>=12&&e*4-Z<=6&&(M>=4||m>=4)&&(I=!0);Z=m*96;r=M*54;b=Z/r<b?Y.height/r:Y.width/Z;b=Math.min(b,2);Z=Math.floor(Math.min(Y.width,Z*b));r=Math.floor(Math.min(Y.height,r*b));Y=this.table.element;Y.ariaLive="polite";g.HM(Y,Z,r);g.I_(Y,{marginLeft:Z/-2+"px",marginTop:r/-2+"px"});this.L.zl(g.HG(this.videoData));this.L instanceof s$&&rC(this.L);g.Zn(this.element,"ytp-endscreen-takeover",
U$(this));VD(this);Z+=4;r+=4;b=0;Y.ariaBusy="true";for(q=0;q<m;q++)for(F=0;F<M;F++)if(C=b,H=0,I&&q>=m-2&&F>=M-2?H=1:F%2===0&&q%2===0&&(F<2&&q<2?F===0&&q===0&&(H=2):H=2),C=g.e9(C+this.D,e),H!==0){R=this.stills[b];R||(R=new Wz(this.player),this.stills[b]=R,Y.appendChild(R.element));var W=Math.floor(r*F/M),N=Math.floor(Z*q/m),y=Math.floor(r*(F+H)/M)-W-4,n=Math.floor(Z*(q+H)/m)-N-4;g.ql(R.element,N,W);g.HM(R.element,n,y);g.I_(R.element,"transitionDelay",(F+q)/20+"s");g.Zn(R.element,"ytp-videowall-still-mini",
H===1);g.Zn(R.element,"ytp-videowall-still-large",H>2);H=Math.max(n,y);g.Zn(R.element,"ytp-videowall-still-round-large",H>=256);g.Zn(R.element,"ytp-videowall-still-round-medium",H>96&&H<256);g.Zn(R.element,"ytp-videowall-still-round-small",H<=96);C=t[C];R.suggestion!==C&&(R.suggestion=C,H=R.api.K(),W=g.bt(R.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.gE(R,C,W),g.lj(H)&&!R.api.U("web_player_log_click_before_generating_ve_conversion_params")&&(H=C.QS(),W={},g.Nv(R.api,"addEmbedsConversionTrackingParams",
[W]),H=g.Bm(H,W),R.updateValue("url",H)),(C=(C=C.sessionData)&&C.itct)&&R.api.setTrackingParams(R.element,C));b++}Y.ariaBusy="false";g.Zn(this.element,"ytp-endscreen-paginate",b<e);for(t=this.stills.length-1;t>=b;t--)m=this.stills[t],g.hS(m.element),g.kZ(m);this.stills.length=b}};
g.k.onVideoDataChange=function(){var m=this.player.getVideoData(1);this.videoData!==m&&(m!=null&&g.HG(m)?(this.D=0,this.videoData=m,this.Oc()):this.player.It("missg",{vid:(m==null?void 0:m.videoId)||"",cpn:(m==null?void 0:m.clientPlaybackNonce)||""}))};
g.k.tT=function(){this.D+=this.stills.length;this.Oc()};
g.k.Ha=function(){this.D-=this.stills.length;this.Oc()};
g.k.TB=function(){return this.L.CO()};
g.k.aK=function(m){m===1?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.L.Fh(),this.Bn&&this.Oc()):(this.C=!0,this.Bn&&U$(this)&&(m===2?this.L.tJ():m===3&&this.L.tL()))};
g.k.yp=function(m){if(m){for(m=0;m<this.stills.length;m++)this.G.logVisibility(this.stills[m].element,!0);this.aK(1)}else this.B=null,this.C=!1;this.Oc()};
g.k.I2=function(){return this.Bn&&U$(this)};g.V(pBf,g.a);g.k=pBf.prototype;g.k.A1=function(){switch(this.buttonType){case 1:var m="Mirar de nuevo en YouTube";var M=156915;break;case 2:m="Seguir mirando en YouTube";M=156942;break;default:m="Seguir mirando en YouTube",M=156942}this.update({content:m});this.G.hasVe(this.element)&&this.G.destroyVe(this.element);this.G.createClientVe(this.element,this,M)};
g.k.onClick=function(m){this.G.U("web_player_log_click_before_generating_ve_conversion_params")&&this.G.logClick(this.element);g.Uo(this.getVideoUrl(),this.G,m);this.G.U("web_player_log_click_before_generating_ve_conversion_params")||this.G.logClick(this.element)};
g.k.getVideoUrl=function(){var m=!0;switch(this.buttonType){case 1:m=!0;break;case 2:m=!1}m=this.G.getVideoUrl(m,!1,!1,!0);var M=this.G.K();if(g.lj(M)){var e={};g.lj(M)&&g.Nv(this.G,"addEmbedsConversionTrackingParams",[e]);m=g.Bm(m,e)}return m};
g.k.logVisibility=function(){this.G.logVisibility(this.element,this.Bn&&this.nE)};
g.k.show=function(){g.a.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.a.prototype.hide.call(this);this.logVisibility()};
g.k.n$=function(m){g.a.prototype.n$.call(this,m);this.logVisibility()};g.V(NO,qO);NO.prototype.hasSuggestions=function(){var m;return(m=this.L)==null?void 0:m.hasSuggestions()};
NO.prototype.show=function(){if(this.player.getPlayerState()!==3){qO.prototype.show.call(this);var m=this.Y;if(m){var M=this.L.hasSuggestions();g.Zn(this.element,"ytp-shorts-branded-ui",M);M?m.show():m.hide()}var e;(e=g.JW(this.player))==null||e.wy(!0);this.player.logVisibility(this.element,!0);this.watchButton.n$(!0)}};
NO.prototype.hide=function(){qO.prototype.hide.call(this);var m;(m=g.JW(this.player))==null||m.wy(!1);this.player.logVisibility(this.element,!1);this.watchButton.n$(!1)};g.V(Duy,g.Fh);g.k=Duy.prototype;g.k.a7=function(){var m=this.player.getVideoData(),M=m.mutedAutoplay&&(m.limitedPlaybackDurationInSeconds>0||m.endSeconds>0||m.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!M)return!0;var e;var I=!!((m==null?0:g.HG(m))||(m==null?0:(e=m.suggestions)==null?0:e.length));I=!lYy(this.player)||I;m=m.Rv;e=this.player.Mv();return I&&!m&&!e&&!M};
g.k.I2=function(){return this.endScreen.I2()};
g.k.m7t=function(){return this.I2()?this.endScreen.TB():!1};
g.k.AG=function(){this.player.al("endscreen");g.Fh.prototype.AG.call(this)};
g.k.load=function(){var m=this.player.getVideoData();var M=m.transitionEndpointAtEndOfStream;if(M&&M.videoId){var e=this.player.aV().ME.get("heartbeat"),I=g.HG(m);!I||M.videoId!==I.videoId||m.aM?(this.player.XX(M.videoId,void 0,void 0,!0,!0,M),e&&e.F4("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),m=!0):m=!1}else m=!1;m||(g.Fh.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.Fh.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(m){this.a7()&&(this.endScreen.created||this.endScreen.create(),m.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(m){m.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){ART(this);this.D&&xuZ(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.L?this.endScreen=new FY(this.player):this.endScreen=new k9(this.player),g.D(this,this.endScreen),g.GS(this.player,this.endScreen.element,4))};g.Zw("endscreen",Duy);})(_yt_player);
